management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,swagger-ui"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enable: true
    app:
      name: "Transactional API"
      version: 1.0.0
      description: "API responsible for managing transactions and statistics"
    metrics:
      tags:
        application: itau-api
  metrics:
    enable:
      all: true

springdoc:
  show-actuator: true